---
title: "DEseq2" 
format: html 
editor: visual
---

```{r}
#| message: false  

# Load libraries library("tidyverse") 
library("DESeq2")  

load(file = "/home/projects/exam_2025_22140_22150/group_2/data/hippocampus_data.Rdata")
load(file = "/home/projects/exam_2025_22140_22150/group_2/data/additional_data.Rdata")
```

## Decide on which dataset to work on!

Also, do not forget to change contrast names when generating results!

DELETE gender for GSE53697,GSE53699!

```{r}
# Change study id here

# You can choose from:
#   Primary datasets: GSE173955; GSE67333  
#   Additional datasets: GSE228458,GSE228459; GSE53697,GSE53699; GSE95587

study_id <- 'GSE95587'
metadata <- `GSE95587_metadata`
isoform <- `GSE95587_isoform`
transcript <- `GSE95587_transcript`
```

# Standard Differential Gene Expression

```{r}
# Synchronize the count matrix with the metadata 
samples_metadata <-   
  metadata$sample_id 
missing_cols <-   
  setdiff(colnames(transcript),           
          samples_metadata) 
transcript <-    
  transcript[, !(colnames(transcript) %in% missing_cols)] 
```

```{r}
# Check if re-arrangement is needed 
all(metadata$sample_id == colnames(transcript))
```

```{r}
# Factorize conditions and gender 
metadata$conditions <-    
  factor(metadata$conditions) 
metadata$gender <-   
  factor(metadata$gender)  
```

Corrected cofounder: Gender

```{r}
# Construct DESeqDataSets and print the new objects 
dds <- DESeqDataSetFromMatrix(   
  countData = transcript,  
  colData = metadata,   
  design = ~ conditions + gender) 
```

## Single PCA plot

```{r}
pca_plot <- plotPCA(vst(dds), 
                    intgroup=c("conditions",  
                               "gender"))

ggsave(
  filename = paste0("/home/projects/exam_2025_22140_22150/group_2/plots/",
                    study_id, 
                    "_PCA_plot.png"),
  plot = pca_plot,
  width = 7,
  height = 5,
  dpi = 300
)
```

## **Differential gene expression analysis**

```{r}
# DESeq fitting 
dds_model <-   
  DESeq(dds)
```

### Calculating results

```{r}
# For GSE173955 and GSE67333 conditions are: "healthy" and "diseased"
# For GSE228458,GSE228459:                   "healthy" and "AD"
# For GSE95587 and GSE53697,GSE53699:        "control" and "Alzheimers"

results <- 
  results(dds_model,   
          contrast=c("conditions",    
                     "control",                  
                     "Alzheimers"))  

# Visualise results 
head(results) 
summary(results)
```

## Identify significant genes

```{r}
# Filter: keep only significant padj values
signif_results <-  
  results[!is.na(results$padj)      
                    & results$padj < 0.05, ]  

# Sort by adjusted p-value 
signif_results <-   
  signif_results[order(signif_results$padj), ]

# Extract gene IDs 
signif_genes <-  
  rownames(signif_results)  

# Count number of significant genes 
n_signif <-  
  nrow(signif_results) 
```

## Save results

```{r}
table1 <- paste0(study_id, "_signif_results")
table2 <- paste0(study_id, "_results")

assign(table1, signif_results)
assign(table2, results)

save(list = c(table1, table2),
     file = paste0("/home/projects/exam_2025_22140_22150/group_2/data/",
                   study_id, 
                   "_deseq_result.Rdata"))
```
