---
title: "02b_isoform_analysis_67333"
format: html
---

```{r}
#| message: false
#| warning: false
library(DEXSeq)
library(fgsea)
library(msigdbr)
library(tidyverse)
```

```{r}
library(DEXSeq)

# Ensure metadata rows are in same order as count columns
GSE67333_metadata <- GSE67333_metadata[
    match(colnames(GSE67333_isoform), GSE67333_metadata$sample_id),
]

all(colnames(GSE67333_isoform) == GSE67333_metadata$sample_id)

```

```{r}
head(rownames(GSE67333_isoform))
str(rownames(GSE67333_isoform))

feature_ids <- as.character(rownames(GSE67333_isoform))
```

```{r}

# GSE67333_metadata$gender <- factor(GSE67333_metadata$condition)

isoInfo <- read_rds(
  paste0(
  '/home/projects/22140/exam_data/',
  'Homo_sapiens.GRCh38.107.chr_patch_hapl_scaff_tx_info.Rds'
  )
)
isoInfo <- isoInfo[match(rownames(GSE67333_isoform), isoInfo$transcript_id), ]

dxd <- DEXSeqDataSet(
    countData = GSE67333_isoform,
    sampleData = GSE67333_metadata,
    design = ~ sample + exon + conditions:exon + gender:exon,
    featureID = isoInfo$transcript_id,
    groupID = isoInfo$gene_id
)

```

```{r}
dxd <- estimateSizeFactors(dxd)
dxd <- estimateDispersions(dxd)

```

```{r}

dxd <- testForDEU(dxd)
dxd <- estimateExonFoldChanges(dxd, fitExpToVar = "conditions")


res <- DEXSeqResults(dxd)

GSE67333_isoform_results = res

save(GSE67333_isoform_results, 
     file = "/home/projects/exam_2025_22140_22150/group_2/data/GSE67333_isoform_results.Rdata")
```

```{r}
alpha <- 0.05
# Significant isoforms (rows)
sig_iso <- res[!is.na(res$padj) & res$padj < alpha, ]
n_sig_isoforms <- nrow(sig_iso)
n_sig_isoforms

n_sig_genes <- length(unique(sig_iso$groupID))
n_sig_genes
```

```{r}
dexseq_df <- as.data.frame(res)
dexseq_df <- dexseq_df[order(dexseq_df$padj), ]
top5_genes <- dexseq_df$groupID[!is.na(dexseq_df$padj)][1:6]

top5_genes
```
